In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

train = pd.read_csv("/kaggle/input/credresolve/train.csv")
test = pd.read_csv("/kaggle/input/credresolve/test.csv")
train.head()

   id      lead_code   suggested_action  TARGET
0   1  LDSMFG_100000  ACTION_HUMAN_CALL    0.47
1   2  LDSMFG_100001       ACTION_FIELD    0.35
2   3  LDSMFG_100002  ACTION_HUMAN_CALL    0.09
3   4  LDSMFG_100003     ACTION_DIGITAL    0.40
4   5  LDSMFG_100004  ACTION_HUMAN_CALL    0.49

In [14]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                80000 non-null  int64
 1   lead_code         80000 non-null  object
 2   suggested_action  80000 non-null  object
 3   TARGET            80000 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 2.4+ MB

In [15]:
train['lead_code'].unique

<bound method Series.unique of 0        LDSMFG_100000
1        LDSMFG_100001
2        LDSMFG_100002
3        LDSMFG_100003
4        LDSMFG_100004
             ...
79995    LDSMFG_179995
79996    LDSMFG_179996
79997    LDSMFG_179997
79998    LDSMFG_179998
79999    LDSMFG_179999
Name: lead_code, Length: 80000, dtype: object>

In [17]:
train['lead_code'].nunique()

80000

In [20]:
train.groupby('lead_code')['suggested_action'].nunique().value_counts()

suggested_action
1    80000
Name: count, dtype: int64

In [2]:
borrowers = pd.read_csv("/kaggle/input/credresolve/metaData.csv")
whatsapp = pd.read_csv("/kaggle/input/credresolve/whatsapp_activity.csv")
ai_call = pd.read_csv("/kaggle/input/credresolve/teleco_call_back.csv")
human_call = pd.read_csv("/kaggle/input/credresolve/call_placed.csv")
agent_visit = pd.read_csv("/kaggle/input/credresolve/mobile_app_data.csv")
ai_sms = pd.read_csv("/kaggle/input/credresolve/AI_sms_callback.csv")

In [4]:
borrowers.head()

       lead_code  total_due dpd_bucket       state
0  LDSMFG_100000     126958      60-90   Karnataka
1  LDSMFG_100001     151867      30-60          UP
2  LDSMFG_100002     136932      60-90       Delhi
3  LDSMFG_100003     370838      30-60  Tamil Nadu
4  LDSMFG_100004     264178      60-90       Delhi

In [3]:
borrowers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   lead_code   100000 non-null  object
 1   total_due   100000 non-null  int64
 2   dpd_bucket  100000 non-null  object
 3   state       100000 non-null  object
dtypes: int64(1), object(3)
memory usage: 3.1+ MB

In [6]:
borrowers['lead_code'].unique

<bound method Series.unique of 0        LDSMFG_100000
1        LDSMFG_100001
2        LDSMFG_100002
3        LDSMFG_100003
4        LDSMFG_100004
             ...
99995    LDSMFG_199995
99996    LDSMFG_199996
99997    LDSMFG_199997
99998    LDSMFG_199998
99999    LDSMFG_199999
Name: lead_code, Length: 100000, dtype: object>

In [8]:
whatsapp.head()

       lead_code     sent_at     status response_message              read_at
0  LDSMFG_124034  2025-01-10  DELIVERED              NaN                  NaN
1  LDSMFG_143014  2025-01-01  DELIVERED              NaN                  NaN
2  LDSMFG_192539  2025-01-20       READ              NaN  2025-01-20 11:00:00
3  LDSMFG_141327  2025-01-08       READ              NaN  2025-01-08 12:00:00
4  LDSMFG_163053  2025-01-25       READ              NaN  2025-01-25 10:00:00

In [21]:
whatsapp.tail()

,lead_code,sent_at,status,response_message,read_at
249995,LDSMFG_152734,2025-01-07,READ,NaN,2025-01-07 10:00:00
249996,LDSMFG_145404,2025-01-20,READ,NaN,2025-01-20 05:00:00
249997,LDSMFG_159715,2025-01-09,FAILED,NaN,NaN
249998,LDSMFG_126674,2025-01-09,DELIVERED,NaN,NaN
249999,LDSMFG_181165,2025-01-09,DELIVERED,NaN,NaN

In [5]:
whatsapp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   lead_code         250000 non-null  object
 1   sent_at           250000 non-null  object
 2   status            250000 non-null  object
 3   response_message  24928 non-null   object
 4   read_at           125138 non-null  object
dtypes: object(5)
memory usage: 9.5+ MB

In [20]:
whatsapp['lead_code'].nunique()

91783

In [32]:
whatsapp.groupby('lead_code')['sent_at'].nunique.value_counts()

lead_code      sent_at
LDSMFG_100000  2025-01-06    1
               2025-01-27    1
               2025-01-30    1
LDSMFG_100002  2025-01-09    1
               2025-01-10    1
                            ..
LDSMFG_199998  2025-01-25    1
               2025-01-27    1
               2025-01-29    1
LDSMFG_199999  2025-01-09    1
               2025-01-13    1
Name: count, Length: 239735, dtype: int64

In [26]:
whatsapp.groupby("lead_code").nunique()

               sent_at  status  response_message  read_at
lead_code
LDSMFG_100000        3       2                 0        2
LDSMFG_100002        3       1                 0        0
LDSMFG_100003        2       1                 0        0
LDSMFG_100004        3       2                 0        2
LDSMFG_100005        3       2                 0        2
...                ...     ...               ...      ...
LDSMFG_199994        2       2                 0        1
LDSMFG_199995        2       2                 1        1
LDSMFG_199996        1       1                 0        0
LDSMFG_199998        6       2                 1        4
LDSMFG_199999        2       1                 0        2

[91783 rows x 4 columns]

In [33]:
whatsapp.sort_values(by="lead_code", ascending=True).head()

,lead_code,sent_at,status,response_message,read_at
218527,LDSMFG_100000,2025-01-06,FAILED,NaN,NaN
173378,LDSMFG_100000,2025-01-30,READ,NaN,2025-01-30 08:00:00
58588,LDSMFG_100000,2025-01-27,READ,NaN,2025-01-27 16:00:00
115149,LDSMFG_100002,2025-01-10,DELIVERED,NaN,NaN
117755,LDSMFG_100002,2025-01-09,DELIVERED,NaN,NaN

In [9]:
ai_call.head()

       lead_code call_type disposition  duration  start_time transcript_json
0  LDSMFG_169928       BOT        BUSY        62  2025-01-03              {}
1  LDSMFG_118994       BOT   NO_ANSWER       153  2025-01-18              {}
2  LDSMFG_196829       BOT   NO_ANSWER       220  2025-01-12              {}
3  LDSMFG_138730       BOT   NO_ANSWER       196  2025-01-04              {}
4  LDSMFG_175894       BOT   NO_ANSWER       133  2025-01-10              {}

In [18]:
ai_call[ai_call['disposition']=="ANSWERED"]

,lead_code,call_type,disposition,duration,start_time,transcript_json
6,LDSMFG_180654,BOT,ANSWERED,181,2025-01-03,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
8,LDSMFG_135728,BOT,ANSWERED,53,2025-01-07,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
11,LDSMFG_158932,BOT,ANSWERED,57,2025-01-28,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
14,LDSMFG_101357,BOT,ANSWERED,44,2025-01-25,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
17,LDSMFG_163871,BOT,ANSWERED,239,2025-01-23,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
...,...,...,...,...,...,...
75045,LDSMFG_149494,BOT,ANSWERED,210,2025-01-15,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
75047,LDSMFG_162118,BOT,ANSWERED,276,2025-01-15,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
75049,LDSMFG_180073,BOT,ANSWERED,256,2025-01-20,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
75050,LDSMFG_144427,BOT,ANSWERED,104,2025-01-23,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"
75052,LDSMFG_170903,BOT,ANSWERED,101,2025-01-07,"{""intent"": ""PTP"", ""sentiment"": ""positive""}"

In [10]:
ai_call.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75055 entries, 0 to 75054
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   lead_code        75055 non-null  object
 1   call_type        75055 non-null  object
 2   disposition      75055 non-null  object
 3   duration         75055 non-null  int64
 4   start_time       75055 non-null  object
 5   transcript_json  75055 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.4+ MB

In [22]:
ai_call['lead_code'].nunique()

52709

In [10]:
human_call.head()

       lead_code call_type disposition  duration  start_time agent_id
0  LDSMFG_165406     HUMAN   NO_ANSWER       195  2025-01-11   AG_117
1  LDSMFG_193330     HUMAN   NO_ANSWER       208  2025-01-23   AG_146
2  LDSMFG_130724     HUMAN   NO_ANSWER       100  2025-01-29   AG_120
3  LDSMFG_138711     HUMAN        BUSY        89  2025-01-26   AG_101
4  LDSMFG_153922     HUMAN    ANSWERED       229  2025-01-15   AG_133

In [11]:
human_call.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74945 entries, 0 to 74944
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   lead_code    74945 non-null  object
 1   call_type    74945 non-null  object
 2   disposition  74945 non-null  object
 3   duration     74945 non-null  int64
 4   start_time   74945 non-null  object
 5   agent_id     74945 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.4+ MB

In [11]:
agent_visit.head()

,lead_code,visit_date,latitude,longitude,result,remarks
0,LDSMFG_165067,2025-01-08,21.555155,77.611374,MET_CUSTOMER,Visited location
1,LDSMFG_179028,2025-01-23,19.801361,77.559830,SHIFTED,Visited location
2,LDSMFG_103580,2025-01-24,18.338005,77.592332,MET_CUSTOMER,Visited location
3,LDSMFG_114426,2025-01-07,21.868144,77.775007,DOOR_LOCKED,Visited location
4,LDSMFG_170042,2025-01-13,14.782281,77.530485,DOOR_LOCKED,Visited location

In [14]:
agent_visit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   lead_code   30000 non-null  object
 1   visit_date  30000 non-null  object
 2   latitude    30000 non-null  float64
 3   longitude   30000 non-null  float64
 4   result      30000 non-null  object
 5   remarks     30000 non-null  object
dtypes: float64(2), object(4)
memory usage: 1.4+ MB

In [12]:
ai_sms.head()

       lead_code     status
0  LDSMFG_110186  DELIVERED
1  LDSMFG_144016  DELIVERED
2  LDSMFG_105785  DELIVERED
3  LDSMFG_113650  DELIVERED
4  LDSMFG_121954  DELIVERED

In [15]:
ai_sms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lead_code  1000 non-null   object
 1   status     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [23]:
import json

ai_call["start_time"] = pd.to_datetime(ai_call["start_time"])
ai_call["duration"] = ai_call["duration"].fillna(0)

def parse_transcript(row):
    try:
        d = json.loads(row)
        return pd.Series({
            "intent": d.get("intent"),
            "sentiment": d.get("sentiment")
        })
    except:
        return pd.Series({"intent": None, "sentiment": None})

ai_call[["intent", "sentiment"]] = ai_call["transcript_json"].apply(parse_transcript)

In [24]:
ai_call.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75055 entries, 0 to 75054
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   lead_code        75055 non-null  object
 1   call_type        75055 non-null  object
 2   disposition      75055 non-null  object
 3   duration         75055 non-null  int64
 4   start_time       75055 non-null  datetime64[ns]
 5   transcript_json  75055 non-null  object
 6   intent           20081 non-null  object
 7   sentiment        20081 non-null  object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 4.6+ MB

In [7]:
ai_call.head()

,lead_code,call_type,disposition,duration,start_time,transcript_json,intent,sentiment
0,LDSMFG_169928,BOT,BUSY,62,2025-01-03,{},None,None
1,LDSMFG_118994,BOT,NO_ANSWER,153,2025-01-18,{},None,None
2,LDSMFG_196829,BOT,NO_ANSWER,220,2025-01-12,{},None,None
3,LDSMFG_138730,BOT,NO_ANSWER,196,2025-01-04,{},None,None
4,LDSMFG_175894,BOT,NO_ANSWER,133,2025-01-10,{},None,None

In [25]:
whatsapp.head()

       lead_code     sent_at     status response_message              read_at
0  LDSMFG_124034  2025-01-10  DELIVERED              NaN                  NaN
1  LDSMFG_143014  2025-01-01  DELIVERED              NaN                  NaN
2  LDSMFG_192539  2025-01-20       READ              NaN  2025-01-20 11:00:00
3  LDSMFG_141327  2025-01-08       READ              NaN  2025-01-08 12:00:00
4  LDSMFG_163053  2025-01-25       READ              NaN  2025-01-25 10:00:00

In [35]:
whatsapp["sent_at"]=pd.to_datetime(whatsapp["sent_at"])
whatsapp["read_at"]=pd.to_datetime(whatsapp["read_at"])

whatsapp["is_read"]=whatsapp['read_at'].notna().astype(int)
whatsapp["has_response"]=whatsapp["response_message"].notna().astype(int)

wa_agg = whatsapp.groupby("lead_code").agg(
    wa_msg_sent_count=("sent_at", "count"),
    wa_msg_read_count=("is_read", "sum"),
    wa_any_response=("has_response", "max"),
    wa_num_responses=("has_response", "sum"),
    wa_last_seen=("sent_at", "max"),
)

wa_agg['wa_read_ratio']=wa_agg["wa_msg_read_count"]/wa_agg["wa_msg_sent_count"]
wa_agg["wa_read_ratio"]=wa_agg["wa_read_ratio"].fillna(0)

In [39]:
ai_call["start_time"] = pd.to_datetime(ai_call["start_time"])

ai_call["is_answered"] = (ai_call["disposition"] == "ANSWERED").astype(int)
ai_call["is_busy"] = (ai_call["disposition"] == "BUSY").astype(int)
ai_call["is_noanswer"] = (ai_call["disposition"] == "NO_ANSWER").astype(int)
ai_call["is_ptp"] = (ai_call["intent"] == "PTP").astype(int)
ai_call["is_pos_sent"] = (ai_call["sentiment"] == "positive").astype(int)

bot_agg = ai_call.groupby("lead_code").agg(
    bot_call_count=("start_time", "count"),
    bot_answered_count=("is_answered", "sum"),
    bot_busy_count=("is_busy", "sum"),
    bot_noanswer_count=("is_noanswer", "sum"),
    bot_total_duration=("duration", "sum"),
    bot_ptp_count=("is_ptp", "sum"),
    bot_positive_sentiment_count=("is_pos_sent", "sum"),
    bot_last_call_time=("start_time", "max")
)

bot_agg["bot_answer_rate"] = bot_agg["bot_answered_count"] / bot_agg["bot_call_count"]
bot_agg["bot_answer_rate"] = bot_agg["bot_answer_rate"].fillna(0)
bot_agg["bot_avg_duration"] = bot_agg["bot_total_duration"] / bot_agg["bot_call_count"]
bot_agg["bot_avg_duration"] = bot_agg["bot_avg_duration"].fillna(0)

In [ ]:
human = human_call.copy()

human["start_time"] = pd.to_datetime(human["start_time"], errors="coerce")

human["duration"] = human["duration"].fillna(0)

human["is_answered"] = (human["disposition"] == "ANSWERED").astype(int)
human["is_noanswer"] = (human["disposition"] == "NO_ANSWER").astype(int)
human["is_busy"] = (human["disposition"] == "BUSY").astype(int)

human_agg = human.groupby("lead_code").agg(
    human_call_count=("start_time", "count"),
    human_answered_count=("is_answered", "sum"),
    human_noanswer_count=("is_noanswer", "sum"),
    human_busy_count=("is_busy", "sum"),
    human_total_duration=("duration", "sum"),
    human_unique_agents=("agent_id", "nunique"),
    human_last_call_time=("start_time", "max"),
)

human_agg["human_avg_duration"] = (
    human_agg["human_total_duration"] / human_agg["human_call_count"]
).fillna(0)

human_agg = human_agg.fillna(0)

In [40]:
agent_visit["visit_date"] = pd.to_datetime(agent_visit["visit_date"])
agent_visit["door_locked"] = (agent_visit["result"] == "DOOR_LOCKED").astype(int)
agent_visit["met_customer"] = (agent_visit["result"] == "MET_CUSTOMER").astype(int)
agent_visit["shifted"] = (agent_visit["result"] == "SHIFTED").astype(int)

field_agg = agent_visit.groupby("lead_code").agg(
    field_visit_count=("visit_date", "count"),
    field_door_locked_count=("door_locked", "sum"),
    field_met_customer_count=("met_customer", "sum"),
    field_shifted_count=("shifted", "sum"),
    field_last_visit_date=("visit_date", "max")
)

In [ ]:
sms = ai_sms.copy()

sms["is_delivered"] = (sms["status"] == "DELIVERED").astype(int)
sms["is_failed"] = (sms["status"] == "FAILED").astype(int)

sms_agg = sms.groupby("lead_code").agg(
    sms_count=("status", "count"),
    sms_delivered_count=("is_delivered", "sum"),
    sms_failed_count=("is_failed", "sum"),
    sms_last_status=("status", lambda x: x.iloc[-1] if len(x) > 0 else None)
)

sms_agg["sms_delivery_rate"] = (
    sms_agg["sms_delivered_count"] / sms_agg["sms_count"]
).fillna(0)

sms_agg = sms_agg.fillna(0)

In [44]:
customer_360 = borrowers.set_index("lead_code")

for df in [wa_agg, bot_agg, human_agg, field_agg, sms_agg]:
    customer_360 = customer_360.join(df, how="left")

customer_360 = customer_360.reset_index()

In [45]:
count_cols = [c for c in customer_360.columns if "count" in c or "duration" in c]
customer_360[count_cols] = customer_360[count_cols].fillna(0)

In [ ]:
# Replace NaN for count columns
for col in ["sms_count", "sms_delivered_count", "sms_failed_count"]:
    customer_360[col] = customer_360[col].fillna(0)

# Replace NaN for status column with a category
customer_360["sms_last_status"] = customer_360["sms_last_status"].fillna("NO_SMS")

# Delivery rate = delivered/sms_count, if sms_count=0, rate=0
customer_360["sms_delivery_rate"] = customer_360["sms_delivery_rate"].fillna(0)

In [59]:
train_merged = train.merge(customer_360, on="lead_code", how="left")
test_merged  = test.merge(customer_360,  on="lead_code", how="left")

In [60]:
X = train_merged.drop(columns=["TARGET", "id"])
y = train_merged["TARGET"]

In [62]:
X.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,lead_code,suggested_action,total_due,dpd_bucket,state,wa_msg_sent_count,wa_msg_read_count,wa_any_response,wa_num_responses,wa_last_seen,...,field_visit_count,field_door_locked_count,field_met_customer_count,field_shifted_count,field_last_visit_date,sms_count,sms_delivered_count,sms_failed_count,sms_last_status,sms_delivery_rate
0,LDSMFG_100000,ACTION_HUMAN_CALL,126958,60-90,Karnataka,3.0,2.0,0.0,0.0,2025-01-30,...,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,NO_SMS,0.0
1,LDSMFG_100001,ACTION_FIELD,151867,30-60,UP,0.0,0.0,NaN,NaN,NaT,...,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,NO_SMS,0.0
2,LDSMFG_100002,ACTION_HUMAN_CALL,136932,60-90,Delhi,3.0,0.0,0.0,0.0,2025-01-19,...,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,NO_SMS,0.0
3,LDSMFG_100003,ACTION_DIGITAL,370838,30-60,Tamil Nadu,2.0,0.0,0.0,0.0,2025-01-12,...,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,NO_SMS,0.0
4,LDSMFG_100004,ACTION_HUMAN_CALL,264178,60-90,Delhi,3.0,2.0,0.0,0.0,2025-01-30,...,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,NO_SMS,0.0

In [63]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   lead_code                     80000 non-null  object
 1   suggested_action              80000 non-null  object
 2   total_due                     80000 non-null  int64
 3   dpd_bucket                    80000 non-null  object
 4   state                         80000 non-null  object
 5   wa_msg_sent_count             80000 non-null  float64
 6   wa_msg_read_count             80000 non-null  float64
 7   wa_any_response               73439 non-null  float64
 8   wa_num_responses              73439 non-null  float64
 9   wa_last_seen                  73439 non-null  datetime64[ns]
 10  wa_read_ratio                 73439 non-null  float64
 11  bot_call_count                80000 non-null  float64
 12  bot_answered_count            80000 non-null  float64
 13  bot_busy_count                80000 non-null  float64
 14  bot_noanswer_count            80000 non-null  float64
 15  bot_total_duration            80000 non-null  float64
 16  bot_ptp_count                 80000 non-null  float64
 17  bot_positive_sentiment_count  80000 non-null  float64
 18  bot_last_call_time            42214 non-null  datetime64[ns]
 19  bot_answer_rate               42214 non-null  float64
 20  bot_avg_duration              80000 non-null  float64
 21  human_call_count              80000 non-null  float64
 22  human_answered_count          80000 non-null  float64
 23  human_noanswer_count          80000 non-null  float64
 24  human_busy_count              80000 non-null  float64
 25  human_total_duration          80000 non-null  float64
 26  human_unique_agents           42310 non-null  float64
 27  human_last_call_time          42310 non-null  datetime64[ns]
 28  human_avg_duration            80000 non-null  float64
 29  field_visit_count             80000 non-null  float64
 30  field_door_locked_count       80000 non-null  float64
 31  field_met_customer_count      80000 non-null  float64
 32  field_shifted_count           80000 non-null  float64
 33  field_last_visit_date         20742 non-null  datetime64[ns]
 34  sms_count                     80000 non-null  float64
 35  sms_delivered_count           80000 non-null  float64
 36  sms_failed_count              80000 non-null  float64
 37  sms_last_status               80000 non-null  object
 38  sms_delivery_rate             80000 non-null  float64
dtypes: datetime64[ns](4), float64(29), int64(1), object(5)
memory usage: 23.8+ MB

In [ ]:
num_cols = X.select_dtypes(include=['float64', 'int64']).columns
X[num_cols] = X[num_cols].fillna(0)

cat_cols = X.select_dtypes(include=['object']).columns
X[cat_cols] = X[cat_cols].fillna("NONE")

dt_cols = X.select_dtypes(include=['datetime64[ns]']).columns
X[dt_cols] = X[dt_cols].fillna(pd.Timestamp("2000-01-01"))

for col in dt_cols:
    X[col] = X[col].astype('int64') // 10**9

In [65]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   lead_code                     80000 non-null  object
 1   suggested_action              80000 non-null  object
 2   total_due                     80000 non-null  int64
 3   dpd_bucket                    80000 non-null  object
 4   state                         80000 non-null  object
 5   wa_msg_sent_count             80000 non-null  float64
 6   wa_msg_read_count             80000 non-null  float64
 7   wa_any_response               80000 non-null  float64
 8   wa_num_responses              80000 non-null  float64
 9   wa_last_seen                  80000 non-null  int64
 10  wa_read_ratio                 80000 non-null  float64
 11  bot_call_count                80000 non-null  float64
 12  bot_answered_count            80000 non-null  float64
 13  bot_busy_count                80000 non-null  float64
 14  bot_noanswer_count            80000 non-null  float64
 15  bot_total_duration            80000 non-null  float64
 16  bot_ptp_count                 80000 non-null  float64
 17  bot_positive_sentiment_count  80000 non-null  float64
 18  bot_last_call_time            80000 non-null  int64
 19  bot_answer_rate               80000 non-null  float64
 20  bot_avg_duration              80000 non-null  float64
 21  human_call_count              80000 non-null  float64
 22  human_answered_count          80000 non-null  float64
 23  human_noanswer_count          80000 non-null  float64
 24  human_busy_count              80000 non-null  float64
 25  human_total_duration          80000 non-null  float64
 26  human_unique_agents           80000 non-null  float64
 27  human_last_call_time          80000 non-null  int64
 28  human_avg_duration            80000 non-null  float64
 29  field_visit_count             80000 non-null  float64
 30  field_door_locked_count       80000 non-null  float64
 31  field_met_customer_count      80000 non-null  float64
 32  field_shifted_count           80000 non-null  float64
 33  field_last_visit_date         80000 non-null  int64
 34  sms_count                     80000 non-null  float64
 35  sms_delivered_count           80000 non-null  float64
 36  sms_failed_count              80000 non-null  float64
 37  sms_last_status               80000 non-null  object
 38  sms_delivery_rate             80000 non-null  float64
dtypes: float64(29), int64(5), object(5)
memory usage: 23.8+ MB

In [66]:
cat_cols = X.select_dtypes(include=['object']).columns.tolist()
cat_cols

['lead_code', 'suggested_action', 'dpd_bucket', 'state', 'sms_last_status']

In [ ]:
X = X.drop(columns=["lead_code"])

cat_cols = X.select_dtypes(include=['object']).columns.tolist()

cat_idx = [X.columns.get_loc(c) for c in cat_cols]

from catboost import CatBoostRegressor

model = CatBoostRegressor(
    depth=8,
    learning_rate=0.05,
    iterations=1500,
    loss_function="RMSE",  
    eval_metric="RMSE",
    verbose=200
)

# 4. Fit model
model.fit(X, y, cat_features=cat_idx)

0:	learn: 0.1883033	total: 106ms	remaining: 2m 39s
200:	learn: 0.1625173	total: 8.69s	remaining: 56.2s
400:	learn: 0.1608736	total: 17.8s	remaining: 48.7s
600:	learn: 0.1591962	total: 27.6s	remaining: 41.3s
800:	learn: 0.1575400	total: 37.6s	remaining: 32.8s
1000:	learn: 0.1559127	total: 47.6s	remaining: 23.7s
1200:	learn: 0.1543402	total: 57.6s	remaining: 14.3s
1400:	learn: 0.1528241	total: 1m 7s	remaining: 4.78s
1499:	learn: 0.1520842	total: 1m 12s	remaining: 0us

In [72]:
X_test = test_merged.drop(columns=["id", "lead_code"])
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 38 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   suggested_action              20000 non-null  object
 1   total_due                     20000 non-null  int64
 2   dpd_bucket                    20000 non-null  object
 3   state                         20000 non-null  object
 4   wa_msg_sent_count             20000 non-null  float64
 5   wa_msg_read_count             20000 non-null  float64
 6   wa_any_response               18344 non-null  float64
 7   wa_num_responses              18344 non-null  float64
 8   wa_last_seen                  18344 non-null  datetime64[ns]
 9   wa_read_ratio                 18344 non-null  float64
 10  bot_call_count                20000 non-null  float64
 11  bot_answered_count            20000 non-null  float64
 12  bot_busy_count                20000 non-null  float64
 13  bot_noanswer_count            20000 non-null  float64
 14  bot_total_duration            20000 non-null  float64
 15  bot_ptp_count                 20000 non-null  float64
 16  bot_positive_sentiment_count  20000 non-null  float64
 17  bot_last_call_time            10495 non-null  datetime64[ns]
 18  bot_answer_rate               10495 non-null  float64
 19  bot_avg_duration              20000 non-null  float64
 20  human_call_count              20000 non-null  float64
 21  human_answered_count          20000 non-null  float64
 22  human_noanswer_count          20000 non-null  float64
 23  human_busy_count              20000 non-null  float64
 24  human_total_duration          20000 non-null  float64
 25  human_unique_agents           10489 non-null  float64
 26  human_last_call_time          10489 non-null  datetime64[ns]
 27  human_avg_duration            20000 non-null  float64
 28  field_visit_count             20000 non-null  float64
 29  field_door_locked_count       20000 non-null  float64
 30  field_met_customer_count      20000 non-null  float64
 31  field_shifted_count           20000 non-null  float64
 32  field_last_visit_date         5194 non-null   datetime64[ns]
 33  sms_count                     20000 non-null  float64
 34  sms_delivered_count           20000 non-null  float64
 35  sms_failed_count              20000 non-null  float64
 36  sms_last_status               20000 non-null  object
 37  sms_delivery_rate             20000 non-null  float64
dtypes: datetime64[ns](4), float64(29), int64(1), object(4)
memory usage: 5.8+ MB

In [ ]:
num_cols_test = X_test.select_dtypes(include=['float64', 'int64']).columns
X_test[num_cols] = X_test[num_cols_test].fillna(0)

cat_cols_test = X_test.select_dtypes(include=['object']).columns
X_test[cat_cols_test] = X_test[cat_cols_test].fillna("NONE")

dt_cols_test = X_test.select_dtypes(include=['datetime64[ns]']).columns
X_test[dt_cols_test] = X_test[dt_cols_test].fillna(pd.Timestamp("2000-01-01"))

for col in dt_cols_test:
    X_test[col] = X_test[col].astype('int64') // 10**9

In [76]:
test_preds = model.predict(X_test)

submission = pd.DataFrame({
    "id": test["id"],
    "TARGET": test_preds
})

submission.to_csv("submission.csv", index=False)

In [77]:
!ls -lh /kaggle/working

total 500K
drwxr-xr-x 4 root root 4.0K Nov 30 10:59 catboost_info
-rw-r--r-- 1 root root 493K Nov 30 11:09 submission.csv

In [78]:
import pandas as pd
pd.read_csv("/kaggle/working/submission.csv").head()

      id    TARGET
0  80001  0.469107
1  80002  0.334546
2  80003  0.479874
3  80004  0.554869
4  80005  0.493358